### ISSUE TITLE
How about iGPU encoding and decoding ?

### ISSUE THREAD

**Issue by bk210** [rocaltair/opencore-msi-z490-gaming-plus-10700k-6600xt#1]
多谢大佬的efi，我也打算购入相同的配置。请问核显工作正常吗？

**Comment by rocaltair** [comment]
@bk210 我是最近加的 6600xt 显卡，之前用的另一套 EFI 可以支持核显 ，不过不支持 monterey 。

基本上你直接用黑果小兵的镜像没有太大问题，需要注意的是我特别标记出来的那几个硬件 quirk。

如果插 U盘安装出问题就换 USB 口。

另外那个8125B网卡的驱动网上很多说法都是有问题的，这个折腾了我很久，黑果小兵镜像里的也有问题，换成我目录里的就好了。这个主板最麻烦的问题应该就是这个了吧，我是跑到国外论坛里扒出来的。

**Comment by bk210** [comment]
感谢详尽的回复，我比较想了解一下使用您提供的efi独显和核显是否可以同时工作，如下图：
![WX20220225-084008](https://user-images.githubusercontent.com/4556392/155631538-63f4bf07-9302-4caf-8418-d77d63b20aa6.png)
不知是否可以帮忙看下，万分感谢！

**Comment by rocaltair** [comment]
我晚上回去看一下，晚些时候回你，我记得我改过这个值： `AAPL,ig-platform-id`。 如果不生效的话，可以参考网上的教程改。我感觉那个核显有点微不足道了。。。 

具体可以参考这个：[link](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties)

**Comment by bk210** [comment]
嗯嗯，有劳了，靠谱的z490 efi不多了，再次感谢！

**Comment by rocaltair** [comment]
![截屏2022-02-25 下午8 48 38](https://user-images.githubusercontent.com/1501074/155717851-b949b242-5887-48d5-a21f-1cea18652105.png)

**Comment by bk210** [comment]
完美！！！
